version: "3.9"
services:
  xilinx_hw_server:
    restart: unless-stopped
    privileged: true
    image: "ghcr.io/stv0g/hw_server:2021.2"
    volumes:
    - "/dev/bus/usb:/dev/bus/usb"
    ports:
    - "3121:3121"
    depends_on:
    - quemu
  quemu:
    restart: unless-stopped
    privileged: true
    image: "aptman/qus"
    command: -s -- -p x86_64


